<?php
/** @var \Klevu\Troubleshoot\Block\Adminhtml\TroubleshootForm $block */

use Magento\Store\Api\Data\StoreInterface;

?>
<div class="messages">
    <div class="message message-warning">
        <strong>
            <?= $block->escapeHtml(
            __('Data Sync Troubleshooter is being deprecated.')
            ) ?>
        </strong>
        <?= $block->escapeHtml(
            __('Instead, it is recommended to use the "Sync Products" grid to troubleshoot sync details.')
        ) ?>
        <?= $block->escapeHtml(
            __('It can be accessed from Catalog > Klevu Catalog Sync > Sync Products.')
        ) ?>
        <?= $block->escapeHtml(
            __('If you cannot see the module, please reach out to your administrator to request access.')
        ) ?>
    </div>
</div>
<form id="klevu_search_troubleshoot_product_form"
      class="form"
      data-mage-init='{"validation": {}}'
      action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>" method="POST">

    <div class="klevu_troubleshoot_product_form admin__collapsible-block">
        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey() ?>"/>

        <a><?= $block->escapeHtml(__('Data Sync Troubleshooter')) ?></a>
        <p class="kl-mage-troubleshoot-introtext message">
            <?= $block->escapeHtml(
                __('Please use this tool to check the Klevu status of specific products in your store.')
            ) ?>
            <?= $block->escapeHtml(
            // phpcs:ignore Generic.Files.LineLength
                __('It can help identify data integrity issues and why a particular product may not be synchronising with Klevu.')
            ) ?>
            <a href="https://help.klevu.com/support/solutions/articles/5000871467-data-sync-troubleshooter"
               target="_blank">
                <?= $block->escapeHtml(__('Click here to find out more')) ?>
            </a>
        </p>
        <fieldset class="fieldset">
            <div class="field required">
                <label for="kl_store_id" class="label">
                    <span><?= $block->escapeHtml(__('Store View')) ?></span>
                </label>
                <div class="control">
                    <select name="kl_store_id"
                            class="input-select select required-entry validate-select"
                            id="kl_store_id"
                            data-validate="{required:true}"
                    >
                        <?php $data = $block->getStoreSelectData() ?>
                        <?php foreach ($data as $website => $groups): ?>
                            <optgroup label="<?= $block->escapeHtml($website) ?>"></optgroup>
                            <?php foreach ($groups as $group => $stores): ?>
                                <optgroup label="<?= $block->escapeHtml($group) ?>">
                                    <?php foreach ($stores as $store): ?>
                                        <?php /** @var StoreInterface $store */ ?>
                                        <option value="<?= $store->getId() ?>">
                                            <?php echo $block->escapeHtml($store->getName()) ?>
                                        </option>
                                    <?php endforeach; ?>
                                </optgroup>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    </select>
                    <p class="note">
                        <span>
                            <?= $block->escapeHtml(
                                __('Select the Store View you would like to check for data sync issues.')
                            ) ?>
                            <?= $block->escapeHtml(
                                __('Only stores with a valid Klevu configuration will appear in this list.')
                            ) ?>
                        </span>
                    </p>
                </div>
            </div>

            <div class="field required">
                <label for="kl_product_id" class="label">
                    <span><?= $block->escapeHtml(__('Product ID')) ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="kl_product_id"
                           id="kl_product_id"
                           class="input-text required-entry"
                           placeholder="Enter a Product ID, eg. 123"
                    />
                    <p class="note">
                        <span>
                            <?= $block->escapeHtml(
                                __('Enter the ID of a Product you would like to check, eg. 123.')
                            ) ?>
                            <?= $block->escapeHtml(
                            // phpcs:ignore Generic.Files.LineLength
                                __('For Configurable products, please enter one of it\'s Child/Variant IDs rather than the Parent ID.')
                            ) ?>
                        </span>
                    </p>
                </div>
            </div>

            <div class="field"><label class="label"></label>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="button"
                                title="Submit"
                                class="action submit primary"
                                id="kl_troubleshoot_submit_button"
                        >
                            <span><?= $block->escapeHtml(__('Submit')) ?></span>
                        </button>
                        <input type="reset"
                               class="action abs-action-primary"
                               title="Reset"
                               id="kl_troubleshoot_reset_button"/>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</form>

<div id="kl_troubleshoot_error" class="kl-mage-finding-empty error"></div>
<div id="kl_troubleshoot_response">&nbsp;</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Klevu_Troubleshoot/js/dataTroubleshoot":{
                "url":"<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            }
        }
    }

</script>
